name: Déploiement local avec runner self-hosted

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Construire l’image Docker
        run: |
          docker rm -f uam-nginx || true
          docker build -t uam-nginx .

      - name: Scanner l’image Docker avec Trivy (format tableau)
        run: |
          trivy image --severity CRITICAL,HIGH,MEDIUM,LOW uam-nginx

      - name: Scanner l’image Docker avec Trivy (rapport JSON)
        run: |
          trivy image --format json --output trivy-report.json uam-nginx

      - name: Afficher le rapport Trivy JSON
        run: |
          cat trivy-report.json

      - name: Lancer le conteneur Docker
        run: |
          docker run -d --name uam-nginx -p 30081:80 uam-nginx