name: Déploiement local sur MacBook

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer la clé SSH privée
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Afficher les variables SSH
        run: |
          echo "SSH_HOST=${{ secrets.SSH_HOST }}"
          echo "SSH_PORT=${{ secrets.SSH_PORT }}"

      - name: Ajouter l’hôte SSH dans known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts || true

      - name: Tester la connectivité SSH (ping)
        run: ping -c 3 ${{ secrets.SSH_HOST }}

      - name: Copier les fichiers vers le MacBook
        run: |
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/uam_deploy

      - name: Construire et lancer le conteneur sur le MacBook
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd /home/${{ secrets.SSH_USER }}/uam_deploy
            docker rm -f uam-nginx || true
            docker build -t uam-nginx .
            docker run -d --name uam-nginx -p 30081:80 uam-nginx
          EOF
