name: Déploiement local avec runner self-hosted

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Construire et lancer le conteneur Docker localement
        run: |
          docker rm -f uam-nginx || true
          docker build -t uam-nginx .
          docker run -d --name uam-nginx -p 30081:80 uam-nginx
